- id: deplic
  name: dep-license
  description: "dep-license: Report license information for dependencies in use by a Python project"
  entry: deplic
  language: python
  require_serial: true
  types: [text]
  files: (requirements.*\.txt$|setup.py$|Pipfile$|pyproject.toml$)
